#make msm8930_cane_defconfig VARIANT_DEFCONFIG=msm8930_cane_wilcox_eur_lte_defconfig SELINUX_DEFCONFIG=selinux_defconfig
make VARIANT_DEFCONFIG=msm8930_cane_wilcox_eur_lte_defconfig SELINUX_DEFCONFIG=selinux_defconfig msm8930_cane_defconfig
